<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260930200116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE food_reference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, calories_per100g DOUBLE PRECISION NOT NULL, proteins_per100g DOUBLE PRECISION NOT NULL, carbs_per100g DOUBLE PRECISION NOT NULL, fats_per100g DOUBLE PRECISION NOT NULL, source VARCHAR(20) NOT NULL, barcode VARCHAR(64) DEFAULT NULL, group_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3659248897AE0266 ON food_reference (barcode)');
        $this->addSql('CREATE INDEX IDX_36592488FE54D947 ON food_reference (group_id)');
        $this->addSql('CREATE INDEX IDX_36592488B03A8386 ON food_reference (created_by_id)');
        $this->addSql('CREATE TABLE fridge_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, storage_location VARCHAR(10) NOT NULL, quantity DOUBLE PRECISION NOT NULL, unit VARCHAR(20) NOT NULL, expiration_date DATE NOT NULL, added_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, group_id INT NOT NULL, food_reference_id INT NOT NULL, added_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_170F6F16FE54D947 ON fridge_item (group_id)');
        $this->addSql('CREATE INDEX IDX_170F6F166A3887C8 ON fridge_item (food_reference_id)');
        $this->addSql('CREATE INDEX IDX_170F6F1655B127A4 ON fridge_item (added_by_id)');
        $this->addSql('CREATE TABLE nutrition_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sex VARCHAR(10) NOT NULL, birth_date DATE NOT NULL, height_cm DOUBLE PRECISION NOT NULL, weight_kg DOUBLE PRECISION NOT NULL, activity_level VARCHAR(20) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_78F3AB5DA76ED395 ON nutrition_profile (user_id)');
        $this->addSql('ALTER TABLE food_reference ADD CONSTRAINT FK_36592488FE54D947 FOREIGN KEY (group_id) REFERENCES app_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE food_reference ADD CONSTRAINT FK_36592488B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fridge_item ADD CONSTRAINT FK_170F6F16FE54D947 FOREIGN KEY (group_id) REFERENCES app_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fridge_item ADD CONSTRAINT FK_170F6F166A3887C8 FOREIGN KEY (food_reference_id) REFERENCES food_reference (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fridge_item ADD CONSTRAINT FK_170F6F1655B127A4 FOREIGN KEY (added_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nutrition_profile ADD CONSTRAINT FK_78F3AB5DA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE food_reference DROP CONSTRAINT FK_36592488FE54D947');
        $this->addSql('ALTER TABLE food_reference DROP CONSTRAINT FK_36592488B03A8386');
        $this->addSql('ALTER TABLE fridge_item DROP CONSTRAINT FK_170F6F16FE54D947');
        $this->addSql('ALTER TABLE fridge_item DROP CONSTRAINT FK_170F6F166A3887C8');
        $this->addSql('ALTER TABLE fridge_item DROP CONSTRAINT FK_170F6F1655B127A4');
        $this->addSql('ALTER TABLE nutrition_profile DROP CONSTRAINT FK_78F3AB5DA76ED395');
        $this->addSql('DROP TABLE food_reference');
        $this->addSql('DROP TABLE fridge_item');
        $this->addSql('DROP TABLE nutrition_profile');
    }
}
