<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007152610 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table meal_plan_entry (planning de repas)';
    }

    public function up(Schema $schema): void
    {
        // NOTE : le diff auto-généré voulait aussi DROP water_goal/water_intake
        // (tables de la branche fix/revue-frontend, pas encore mergée dans
        // develop — absentes des entités Doctrine de CETTE branche mais bien
        // réelles en base partagée). Retiré à la main : cette migration ne
        // doit toucher que meal_plan_entry, pas détruire les données d'une
        // autre branche en cours.
        $this->addSql('CREATE TABLE meal_plan_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, meal_type VARCHAR(10) NOT NULL, servings INT NOT NULL, group_id INT NOT NULL, recipe_id INT NOT NULL, added_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EFEB6E06FE54D947 ON meal_plan_entry (group_id)');
        $this->addSql('CREATE INDEX IDX_EFEB6E0659D8A214 ON meal_plan_entry (recipe_id)');
        $this->addSql('CREATE INDEX IDX_EFEB6E0655B127A4 ON meal_plan_entry (added_by_id)');
        $this->addSql('ALTER TABLE meal_plan_entry ADD CONSTRAINT FK_EFEB6E06FE54D947 FOREIGN KEY (group_id) REFERENCES app_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_plan_entry ADD CONSTRAINT FK_EFEB6E0659D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_plan_entry ADD CONSTRAINT FK_EFEB6E0655B127A4 FOREIGN KEY (added_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE meal_plan_entry DROP CONSTRAINT FK_EFEB6E06FE54D947');
        $this->addSql('ALTER TABLE meal_plan_entry DROP CONSTRAINT FK_EFEB6E0659D8A214');
        $this->addSql('ALTER TABLE meal_plan_entry DROP CONSTRAINT FK_EFEB6E0655B127A4');
        $this->addSql('DROP TABLE meal_plan_entry');
    }
}
