<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007141813 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table water_goal (objectif d\'hydratation personnalisé)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE water_goal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, goal_ml INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_water_goal_user ON water_goal (user_id)');
        $this->addSql('ALTER TABLE water_goal ADD CONSTRAINT FK_6CA25FBAA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE water_goal DROP CONSTRAINT FK_6CA25FBAA76ED395');
        $this->addSql('DROP TABLE water_goal');
    }
}
