<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008212804 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Journal quotidien : DailyNutritionLog (calories/macros consommées par jour) et MealPlanEntryLog (réponse personnelle au pop-up "as-tu mangé ce repas ?").';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_nutrition_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, calories_consumed INT NOT NULL, protein_consumed_g DOUBLE PRECISION NOT NULL, carb_consumed_g DOUBLE PRECISION NOT NULL, fat_consumed_g DOUBLE PRECISION NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_daily_nutrition_log_user_date ON daily_nutrition_log (user_id, date)');
        $this->addSql('CREATE INDEX IDX_D30B30C9A76ED395 ON daily_nutrition_log (user_id)');
        $this->addSql('CREATE TABLE meal_plan_entry_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(10) NOT NULL, replacement_description VARCHAR(255) DEFAULT NULL, replacement_calories DOUBLE PRECISION DEFAULT NULL, replacement_protein_g DOUBLE PRECISION DEFAULT NULL, replacement_carb_g DOUBLE PRECISION DEFAULT NULL, replacement_fat_g DOUBLE PRECISION DEFAULT NULL, applied_calories INT NOT NULL, applied_protein_g DOUBLE PRECISION NOT NULL, applied_carb_g DOUBLE PRECISION NOT NULL, applied_fat_g DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, meal_plan_entry_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_meal_plan_entry_log_entry_user ON meal_plan_entry_log (meal_plan_entry_id, user_id)');
        $this->addSql('CREATE INDEX IDX_28491D07AE6AC4B4 ON meal_plan_entry_log (meal_plan_entry_id)');
        $this->addSql('CREATE INDEX IDX_28491D07A76ED395 ON meal_plan_entry_log (user_id)');
        $this->addSql('ALTER TABLE daily_nutrition_log ADD CONSTRAINT FK_D30B30C9A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_plan_entry_log ADD CONSTRAINT FK_28491D07AE6AC4B4 FOREIGN KEY (meal_plan_entry_id) REFERENCES meal_plan_entry (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_plan_entry_log ADD CONSTRAINT FK_28491D07A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_nutrition_log DROP CONSTRAINT FK_D30B30C9A76ED395');
        $this->addSql('ALTER TABLE meal_plan_entry_log DROP CONSTRAINT FK_28491D07AE6AC4B4');
        $this->addSql('ALTER TABLE meal_plan_entry_log DROP CONSTRAINT FK_28491D07A76ED395');
        $this->addSql('DROP TABLE daily_nutrition_log');
        $this->addSql('DROP TABLE meal_plan_entry_log');
    }
}
