<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007140113 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table water_intake (suivi d\'eau quotidien)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE water_intake (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, amount_ml INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_water_intake_user_date ON water_intake (user_id, date)');
        $this->addSql('CREATE INDEX IDX_77832F8FA76ED395 ON water_intake (user_id)');
        $this->addSql('ALTER TABLE water_intake ADD CONSTRAINT FK_77832F8FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE water_intake DROP CONSTRAINT FK_77832F8FA76ED395');
        $this->addSql('DROP TABLE water_intake');
    }
}
