<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261002185031 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Étape 15 : module Liste de courses (shopping_list, shopping_list_item)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE shopping_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3DC1A459FE54D947 ON shopping_list (group_id)');
        $this->addSql('CREATE TABLE shopping_list_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, quantity DOUBLE PRECISION NOT NULL, unit VARCHAR(20) NOT NULL, calories_per100g DOUBLE PRECISION NOT NULL, proteins_per100g DOUBLE PRECISION NOT NULL, carbs_per100g DOUBLE PRECISION NOT NULL, fats_per100g DOUBLE PRECISION NOT NULL, source_recipe_name VARCHAR(120) DEFAULT NULL, shopping_list_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FB1C22423245BF9 ON shopping_list_item (shopping_list_id)');
        $this->addSql('ALTER TABLE shopping_list ADD CONSTRAINT FK_3DC1A459FE54D947 FOREIGN KEY (group_id) REFERENCES app_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_item ADD CONSTRAINT FK_4FB1C22423245BF9 FOREIGN KEY (shopping_list_id) REFERENCES shopping_list (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE shopping_list DROP CONSTRAINT FK_3DC1A459FE54D947');
        $this->addSql('ALTER TABLE shopping_list_item DROP CONSTRAINT FK_4FB1C22423245BF9');
        $this->addSql('DROP TABLE shopping_list');
        $this->addSql('DROP TABLE shopping_list_item');
    }
}
